services:
  
  shibboleth:
    class: Duke\ShibbolethBundle\Security\Shibboleth
    arguments: ["%shibboleth.login%", "%shibboleth.logout%", "%shibboleth.logout_target%"]
  
  shib.security.authentication.provider:
    class: Duke\ShibbolethBundle\Security\ShibAuthenticationProvider

  shib.security.authentication.listener:
    class: Duke\ShibbolethBundle\Security\ShibListener
    arguments: ["@security.context", "@security.authentication.manager"]
      
  shib.security.entry_point:
    class: Duke\ShibbolethBundle\Security\ShibEntryPoint
    arguments: ["", "@shibboleth"]
      
  shib.security.logout_handler:
    class: Duke\ShibbolethBundle\Security\ShibLogoutHandler
    arguments: ["@shibboleth"]
