services:
  
  shibboleth:
    class: Duke\ShibbolethBundle\Security\Shibboleth
    arguments: ["%shibboleth.login%", "%shibboleth.logout%", "%shibboleth.returnto%"]
  
  shibboleth.security.authentication.provider:
    class: Duke\ShibbolethBundle\Security\ShibbolethAuthenticationProvider

  shibboleth.security.authentication.listener:
    class: Duke\ShibbolethBundle\Security\ShibbolethListener
    arguments: ["@security.context", "@security.authentication.manager"]
      
  shibboleth.security.entry_point:
    class: Duke\ShibbolethBundle\Security\ShibbolethEntryPoint
    arguments: ["", "@shibboleth"]
      
  shibboleth.security.logout_handler:
    class: Duke\ShibbolethBundle\Security\ShibbolethLogoutHandler
    arguments: ["@shibboleth"]
